export enum ERRORS {
    "AUTH_LOGIN_FAILED",
    "AUTH_SIGNUP_FAILED",
    "AUTH_LOGOUT_FAILED",
    "SEARCH_FAILED",
    "FETCHING_USER_FAILED",
    "FETCHING_IMAGE_FAILED",
    "IMAGE_UPLOAD_FAILED",
    "CREATE_TEXT_FAILED",
    "FETCH_ALL_TEXTS_FAILED",
    "FETCH_TEXT_FAILED",
    "UPDATE_TEXT_FAILED",
    "DELETE_TEXT_FAILED",
    "CREATE_TEXT_PAGE_FAILED",
    "CREATE_ALL_TEXT_PAGES_FAILED",
    "FETCH_TEXT_PAGE_FAILED",
    "UPDATE_TEXT_PAGE_FAILED",
    "DELETE_TEXT_PAGE_FAILED",
    "FETCH_USER_FAILED",
    "FETCH_ALL_USERS_FAILED",
    "UPDATE_USER_FAILED",
    "DELETE_USER_FAILED",
}

export function sendError(code: ERRORS, err){
    console.error(code.toString(), err)
}